#!/bin/bash

# ---------------------------------------------------------------------------
# OPENKAROTZ FIRMWARE FOR KAROTZ
#
# INSERT THE USBKEY AND RESTART THE RABBIT
# OR SEND {"cmd":"reboot"} TO ITS SERIAL PORT
#
# ---------------------------------------------------------------------------

BLACK=000000
BLUE=0000FF
CYAN=00FF9F
GREEN=00FF00
ORANGE=FFA500
PINK=FFCFAF
PURPLE=9F00FF
RED=FF0000
VIOLET=660099
WHITE=4FFF68
YELLOW=75FF00

PULSE_FAST=300
PULSE_NORMAL=700
PULSE_SLOW=1500

LED=/karotz/bin/led
MPLAY=/usr/bin/madplay
USB_MP3=/mnt/usbkey/Sounds
LOGFILE=/mnt/usbkey/ok_log_$(date +%Y%m%d).txt

function led_orange_pulse 
{
    killall led
    $LED -l $ORANGE -p 000000 -d 700 &
}

function led_orange
{
    killall led
    $LED -l $ORANGE
}


function led_red {
    killall led
    $LED -l $RED
}

function led_violet_pulse {
    killall led
    $LED -l $VIOLET -p 000000 -d 700 &

}

function led_green {
    killall led
    $LED -l $GREEN
}



function PLAY {
	killall madplay
	$MPLAY $USB_MP3/$1.mp3 $2
}

function LOG {
    echo $(date +"%T : ") $1 >> $LOGFILE
}


if [ -f /mnt/usbkey/updatedone ]; then
    LOG "[USBKEY] ## UPDATE ALREADY DONE"
    exit 0
fi



led_orange
PLAY "start"
sleep 5

if [ ! -e "/mnt/usbkey/rootfs.wizz.120719r2.img.gz" ]; then
 echo "ERROR: Unable to find rootfs file"
 LOG "ERROR: Unable to find rootfs file"
 led_red
 PLAY "error"
 exit 1
fi

if [ ! -e "/mnt/usbkey/rootfs.wizz.120719r2.img.gz.md5" ]; then
  echo "ERROR: Unable to find rootfs signature file"
  LOG "ERROR: Unable to find rootfs signature file"
  led_red
  PLAY "error"
  exit 1
fi

SIGN=$(md5sum /mnt/usbkey/rootfs.wizz.120719r2.img.gz | cut -d' ' -f1)
REF=$(cat /mnt/usbkey/rootfs.wizz.120719r2.img.gz.md5 | cut -d' ' -f1) 

echo "Computed  MD5 :"$SIGN
echo "Reference MD5 :"$REF

if [ "$SIGN" == "$REF" ]; then
  echo "Check : Success"
  LOG "Check success"
  echo "Start Flashing"
else
  echo "Check : Failed"
  LOG "ERROR: check failed $SIGN - $REF"
  echo "Flashing Aborted"
  led_red
  PLAY "error"
  exit 1   
fi

led_orange
PLAY "install"
LOG "Installation"

echo "Erasing Flash"
LOG "Erasing Flash"
/sbin/flash_eraseall /dev/mtd2 

echo "Flashing new firmware"
LOG "Flashing Firmware"
/sbin/nandwrite -pm /dev/mtd2 /mnt/usbkey/rootfs.wizz.120719r2.img.gz
sleep 5

led_green

sleep 30
PLAY "oktermine"

touch /mnt/usbkey/updatedone
echo  "::once:/sbin/reboot" >> /etc/inittab






